### ISSUE TITLE
How does the lattice mode determine output angles?

### ISSUE THREAD

**Issue by lucifer1004** [dmckwski/MSTM#12]
The output says `scattering by periodic lattice at reciprocal lattice directions` but I cannot find related information in the manual. Is there any reference for this determination I could turn to?

Thanks a lot!

**Comment by dmckwski** [comment]
Look at section 2.3.4 of mackowski-mstm-2022b.pdf (in the doc folder).   For a periodic lattice the scattered field will appear as a diffraction pattern: non-zero only at a set of discrete directions.     Those directions are referred to as the reciprocal lattice directions.     

Best regards - Dan
