### ISSUE TITLE
`t_matrix_epsilon` option not supported

### ISSUE THREAD

**Issue by lucifer1004** [dmckwski/MSTM#7]
It is listed in the manual but cannot be found in the code.

**Comment by lucifer1004** [comment]
BTW, there is a duplicate `translation_epsilon` paragraph in P13 of the manual.

**Comment by dmckwski** [comment]
Should be 't_matrix_convergence_epsilon'.   I will fix the manual.   Thanks for finding the duplication!

**Comment by lucifer1004** [comment]
Fixed in the updated manual.
